# Generated by Django 5.2.14 on 2026-10-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_youthinfo_practice_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для рассылки заявок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Получает письма')),
                ('receives_vacancies', models.BooleanField(default=True, verbose_name='Вакансии и подписка с резюме')),
                ('receives_reserve', models.BooleanField(default=True, verbose_name='Кадровый резерв')),
                ('receives_practice', models.BooleanField(default=True, verbose_name='Практика')),
                ('receives_training', models.BooleanField(default=True, verbose_name='Обучение')),
            ],
            options={
                'verbose_name': 'Получатель заявок',
                'verbose_name_plural': 'Получатели заявок',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('competition_type', models.CharField(choices=[('vacancy', 'На замещение вакантной должности'), ('reserve', 'На формирование кадрового резерва')], default='reserve', max_length=20, verbose_name='Для конкурсов')),
                ('file', models.FileField(upload_to='competitions/documents/', verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Нормативный документ конкурсов',
                'verbose_name_plural': 'Нормативные документы конкурсов',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vacancysubscription',
            name='about',
            field=models.TextField(blank=True, verbose_name='О себе, навыки'),
        ),
        migrations.AddField(
            model_name='vacancysubscription',
            name='desired_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Желаемая должность'),
        ),
        migrations.AddField(
            model_name='vacancysubscription',
            name='education',
            field=models.CharField(blank=True, max_length=255, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='vacancysubscription',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='vacancysubscription',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='subscription_resumes/', verbose_name='Файл резюме'),
        ),
        migrations.AddField(
            model_name='vacancysubscription',
            name='work_experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
        migrations.CreateModel(
            name='CompetitionWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=500, verbose_name='Должность / орган')),
                ('description', models.TextField(blank=True, verbose_name='Информация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='competitions/winners/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='api.competitionresult', verbose_name='Результат конкурса')),
            ],
            options={
                'verbose_name': 'Победитель конкурса',
                'verbose_name_plural': 'Победители конкурса',
                'ordering': ['order', 'id'],
            },
        ),
    ]
