# Generated by Django 5.2.14 on 2026-10-05 06:28

import django.utils.timezone
from django.db import migrations, models


def copy_created_date(apps, schema_editor):
    """У существующих вакансий дата публикации = дата создания"""
    Vacancy = apps.get_model('api', 'Vacancy')
    for vacancy in Vacancy.objects.all():
        vacancy.published_at = vacancy.created_at.date()
        vacancy.save(update_fields=['published_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_application_recipients_competition_docs_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата публикации'),
        ),
        migrations.RunPython(copy_created_date, migrations.RunPython.noop),
    ]
