# Generated by Django 5.2.14 on 2026-10-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_vacancy_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, help_text='Необязательно: если поле пустое, оплата в карточке и на странице вакансии не показывается', max_length=255, verbose_name='Оплата труда'),
        ),
    ]
