# Generated by Django 5.2.14 on 2026-10-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_vacancy_salary_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Отдел (для контактов)', 'verbose_name_plural': 'Отделы (для контактов)'},
        ),
        migrations.AlterModelOptions(
            name='contactstaffmember',
            options={'verbose_name': 'Сотрудник (контакты)', 'verbose_name_plural': 'Сотрудники (контакты)'},
        ),
        migrations.AlterModelOptions(
            name='corruptionreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение о коррупции', 'verbose_name_plural': 'Сообщения о коррупции'},
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-created_at'], 'verbose_name': 'Документ раздела «Конкурсы»', 'verbose_name_plural': 'Документы раздела «Конкурсы»'},
        ),
        migrations.AlterModelOptions(
            name='trainingevent',
            options={'ordering': ['event_date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
