# Generated by Django 5.2.14 on 2026-10-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_admin_section_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrecipient',
            name='receives_feedback',
            field=models.BooleanField(default=False, verbose_name='Обратная связь'),
        ),
    ]
