# Generated by Django 5.2.14 on 2026-10-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_vacancy_subscribers_notified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anticorruptioninfo',
            options={'verbose_name': 'Страница «Нет коррупции!»', 'verbose_name_plural': 'Страница «Нет коррупции!»'},
        ),
    ]
