# Generated by Django 5.2.14 on 2026-10-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_anticorruption_page_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short_name', models.CharField(help_text='Для меток и диаграмм.', max_length=120, verbose_name='Короткое название')),
                ('color', models.CharField(choices=[('indigo', 'Индиго'), ('violet', 'Фиолетовый'), ('teal', 'Бирюзовый'), ('emerald', 'Зелёный'), ('amber', 'Янтарный'), ('slate', 'Серый')], default='indigo', max_length=20, verbose_name='Цвет')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория правовых позиций',
                'verbose_name_plural': 'Категории правовых позиций',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EducationLegalAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(help_text='Как в нормах позиций, например «ФЗ-273» или «ГК РФ». Норма «ст. 12 ФЗ-273» автоматически относится к акту «ФЗ-273».', max_length=50, unique=True, verbose_name='Сокращение')),
                ('full_name', models.TextField(verbose_name='Полное название')),
                ('changed_note', models.TextField(blank=True, help_text='Если акт утратил силу или изменён — на странице появится пометка «Норма изменена».', verbose_name='Примечание об изменении')),
            ],
            options={
                'verbose_name': 'Нормативный акт',
                'verbose_name_plural': 'Нормативные акты',
                'ordering': ['abbr'],
            },
        ),
        migrations.CreateModel(
            name='EducationReviewPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Тематический обзор Верховного Суда РФ N 14/2026', max_length=255, verbose_name='Надзаголовок')),
                ('title', models.CharField(default='27 правовых позиций по антикоррупционным делам', max_length=255, verbose_name='Заголовок обзора')),
                ('lead', models.TextField(blank=True, help_text='Абзац под заголовком обзора.', verbose_name='Краткое описание')),
                ('approved_note', models.TextField(blank=True, help_text='Например: «Утверждён постановлением Президиума ВС РФ от 01.07.2026 N 17А/2026».', verbose_name='Реквизиты утверждения')),
                ('period', models.CharField(blank=True, default='2020–2026', help_text='Показывается в блоке цифр.', max_length=50, verbose_name='Период изученной практики')),
                ('intro', models.TextField(blank=True, help_text='Абзацы разделяются пустой строкой. Показывается на вкладке «Полный текст».', verbose_name='Вводная часть обзора')),
                ('source_note', models.TextField(blank=True, help_text='Пояснение внизу страницы: откуда взят материал и какую силу имеет.', verbose_name='Источник')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница «Антикоррупционное просвещение»',
                'verbose_name_plural': 'Страница «Антикоррупционное просвещение»',
            },
        ),
        migrations.CreateModel(
            name='EducationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Номер используется в ссылках и на карточках; по нему же сортируются позиции.', unique=True, verbose_name='Номер позиции')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subjects', models.TextField(blank=True, help_text='Каждый субъект с новой строки.', verbose_name='Кто фигурирует')),
                ('legal_basis', models.TextField(blank=True, help_text='Каждая норма с новой строки, например «ст. 15 ФЗ-25». Нормативный акт определяется по сокращению в конце.', verbose_name='Применённые нормы')),
                ('outcome', models.CharField(blank=True, choices=[('granted', 'Удовлетворено'), ('granted_partly', 'Удовлетворено частично'), ('lawful', 'Признано правомерным'), ('denied', 'Отказано'), ('remanded', 'Направлено на новое рассмотрение'), ('motion_rejected', 'Ходатайство отклонено')], max_length=20, verbose_name='Исход')),
                ('outcome_note', models.CharField(blank=True, max_length=255, verbose_name='Пояснение к исходу')),
                ('in_favor_of_official', models.BooleanField(default=False, verbose_name='Решено в пользу служащего / ответчика')),
                ('municipal', models.BooleanField(default=False, verbose_name='Касается муниципального уровня')),
                ('norm_changed', models.BooleanField(default=False, verbose_name='Норма изменена')),
                ('key_quote', models.TextField(verbose_name='Правовая позиция (дословно)')),
                ('facts_summary', models.TextField(blank=True, verbose_name='Фабула дела')),
                ('lesson', models.TextField(blank=True, verbose_name='Что важно служащему')),
                ('page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Страница в PDF')),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Последний год событий из фабулы. Без года позиция попадёт в колонку «Без дат в фабуле».', null=True, verbose_name='Год на таймлайне')),
                ('years', models.CharField(blank=True, help_text='Например «2020–2023».', max_length=50, verbose_name='Период в фабуле')),
                ('amount', models.PositiveBigIntegerField(blank=True, help_text='Только если обзор называет сумму.', null=True, verbose_name='Сумма, обращённая в доход РФ, ₽')),
                ('full_text', models.TextField(blank=True, help_text='Абзацы разделяются пустой строкой. Знак сноски в тексте — «<1>».', verbose_name='Полный текст позиции')),
                ('notes', models.TextField(blank=True, help_text='Каждая сноска с новой строки в виде «1. Текст сноски».', verbose_name='Сноски')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='api.educationcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Правовая позиция',
                'verbose_name_plural': 'Правовые позиции',
                'ordering': ['number'],
            },
        ),
    ]
