# Generated by Django 5.2.14 on 2026-10-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_education_review_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationreviewpage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Вводная часть обзора'),
        ),
    ]
