# Generated by Django 5.2.14 on 2026-10-07 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_education_intro_markdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('action', models.CharField(choices=[('view', 'Просмотр записи'), ('list', 'Просмотр списка'), ('add', 'Создание записи'), ('change', 'Изменение записи'), ('delete', 'Удаление записи'), ('download', 'Скачивание файла'), ('submit', 'Получено с сайта'), ('transfer', 'Передача по почте'), ('login', 'Вход в админку'), ('login_failed', 'Неудачный вход'), ('logout', 'Выход из админки')], db_index=True, max_length=20, verbose_name='Действие')),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Логин')),
                ('object_type', models.CharField(blank=True, max_length=120, verbose_name='Раздел / тип данных')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='Номер записи')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Браузер')),
                ('details', models.CharField(blank=True, max_length=500, verbose_name='Подробности')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала доступа к ПД',
                'verbose_name_plural': 'Журнал доступа к ПД',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='CorruptionReport',
        ),
    ]
